#!/bin/bash
sudo $1 install build-essential -y
sudo $1  install bison -y
sudo $1  install flex -y
sudo $1  install libgmp3-dev -y
sudo $1  install libmpc-dev -y
sudo $1  install libmpfr-dev -y
sudo $1  install texinfo -y
sudo $1  install libcloog-isl-dev -y
sudo $1  install libisl-dev -y
sudo $1  install qemu  -y
sudo $1  install grub-common -y
sudo $1  install xorriso -y
sudo $1  install nasm -y
sudo $1  install grub-pc-bin -y
sudo $1  install libfontconfig1 -y
sudo $1 install mesa-common-dev -y
sudo $1  install libglu1-mesa-dev -y
sudo $1 update && sudo $1 upgrade -y

export PREFIX="$HOME/opt/cross" export TARGET=i686-elf export PATH="$PREFIX/bin:$PATH" mkdir ~/src
cd ~/src wget https://ftp.gnu.org/gnu/binutils/binutils-2.31.1.tar.xz tar -xf binutils-2.31.1.tar.xz rm binutils-2.31.1.tar.xz mkdir build-binutils cd build-binutils/ ../binutils-2.31.1/configure --target=$TARGET --prefix="$PREFIX"  --with-sysroot --disable-nls --disable-werror make make install
cd ~/src wget https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz tar -xf gcc-8.2.0.tar.xz rm gcc-8.2.0.tar.xz mkdir build-gcc cd build-gcc ../gcc-8.2.0/configure --target=$TARGET --prefix="$PREFIX"  --disable-nls --enable-languages=c,c++ --without-headers make all-gcc make all-target-libgcc make install-gcc make install-target-libgcc
export PATH=$HOME/opt/cross/bin:$PATH


clear
echo -e "if not RUN ! \nenter your package manager \nlike this 'gccCrossPltfrm (yum or apt)'"
sleep 10;
